function disp_tree(tree, depth, Nf)
% DISP_TREE displays the decision tree generated by the C4.5 algorithm

if isstruct(tree.child)
    NODE_TYPE = 'Node';
    % get the number of child nodes
    N = size(tree.child, 2);
    has_child = true;
else
    NODE_TYPE = 'Leaf';isa
    has_child = false;
end

if isequal(depth,0)
    NODE_TYPE = 'Root';
end

PRINT_TEXT = [dashes(2 * depth), NODE_TYPE];

if ~has_child
    PRINT_TEXT = [PRINT_TEXT, '(', num2str(Nf), ')' ,  ' : ',num2str(tree.child)];
    disp(PRINT_TEXT);
    return
end

if isequal(depth,0)
    PRINT_TEXT = [PRINT_TEXT, ' has ', num2str(N), ' child(s)'];
elseif depth > 0
    PRINT_TEXT = [PRINT_TEXT, '(', num2str(Nf), ')' , ' has ', num2str(N), ' child(s)'];
    
end
disp(PRINT_TEXT);

Nf = tree.Nf;

depth = depth + 1;
for i = 1:N
    node = tree.child(i);
    %node.dim
    disp_tree(node,depth,Nf(i))
end
end

